### ISSUE TITLE
Ownfoil doesn't see the games?

### ISSUE THREAD

**Issue by RoyMeinen** [a1ex4/ownfoil#24]
I never used any shop before and since pixel closed their doors. I directly went to Ownfoil. So i'm new and don't understand it all, sorry. The store setup was easy on my QNAP and is running smooth.

So I figured out you need to insert the tinfoil id in the name otherwise there is an loading error in the console log. and a version. 
So my folder + games setup looks like this: 
Gametitle
     /Base/Gametitle [[tinfoil-game-id][v0].nsp
     /Updates/Gametitle [[tinfoil-game-id][v1423].nsp
     /DLC/Gametitle DLCNAME[tinfoil-game-id][v0].nsp

However, I think when im installing in most cases it's just the update i install since i get the "You need the software" message. And in other cases I see that the game is version 1.0 so I can't play or update it?

I'm totally new so, sorry if these are stupid questions, am i doing something wrong?

**Comment by Ninnteen** [comment]
Hi!

This issue is not related to Ownfoil, juste grab the updates for the games you need and grab the base nsp/xci.

**Comment by xF4m3** [comment]
Hey,

I am also wondering on how the Game Library has to look to be correctly identified and used to install games aswell as updates and maybe even DLC'S. I was reading somewhere else to just put all the .nsp files with their respective title id in the name into on giant folder, but is it possible to organize the games similar to RoyMeinen's example? 

So basically having the following folder structure:

```
/games/Base/Gametitle [[tinfoil-game-id][v0].nsp
/games/Updates/Gametitle [[tinfoil-game-id][v1423].nsp
/games/DLC/Gametitle DLCNAME[tinfoil-game-id][v0].nsp
```
If not, it would be nice to have a info in the README.md for how to organize the libary with a small example, even if this is not directly related to this docker container but more related to tinfoil :D

**Comment by sonofsparda757** [comment]
Im also wondering if there are any "shop templates" out there. We need more details on what kind of folder structure tinfoil exactly is expecting. I think big shop owners (or those that used to host one) would know about this. 

Also is it possible to pull metadata and make the shop look like an actual shop instead of just a directory?

**Comment by programatix** [comment]
ownfoil traverse all the sub-directories to detect the supported files for base, dlcs and updates. It doesn't matter how you structured the directories.

**Comment by migm16** [comment]
looks like what has worked for me so far is instead of having ur folder with folders holding each game and its updates or dlc u just gotta take all that and chuck it into a single folder with all the games/updates/dlcs then it should show it in tinfoil as new games, if its an xci i notice there is an xci tab
