### ISSUE TITLE
Separate Directories

### ISSUE THREAD

**Issue by Corban-Lee** [a1ex4/ownfoil#87]
I would like to store files like configs and games separately.
Games on a HDD, configs on an SSD.

Would you be able to separate these files, perhaps into `/games` and `/config`. The user can then mount these directories as desired with docker.

I also see the roadmap and that you wish to store user saves (if I'm understanding it correctly)? Separating files like this will help maintainability and scalability as the project grows to these new scopes.

**Comment by a1ex4** [comment]
Yeah this is exactly how it's done in the `v2` branch, you can check the docker-compose file and the library and config directories are completely separate.

For the save implementation the goal is to have Switch devices registered with the user, so that an user will only access and be served its own saves. They will be saved in a separate repertory for sure.
